#!/bin/sh

# This script is an example of something you might like to do after a
# job is run.  It is set by the HADOOP_POST_JOB_RUN environment
# variable.  See the sbatch.hadoop file for details.
 
# Cleanup some stuff
# rm -rf /ssd/tmp1/achu/

# Cleaning up on networked directory, only do on one node
if [ "${HADOOP_CLUSTER_NODERANK}" == "0" ]
then
    # rm -rf /p/lscratchg/achu/hadoop/hdfsoverlustre/
fi

exit 0