#!/bin/bash
#############################################################################
#  Copyright (C) 2013-2015 Lawrence Livermore National Security, LLC.
#  Produced at Lawrence Livermore National Laboratory (cf, DISCLAIMER).
#  Written by Albert Chu <chu11@llnl.gov>
#  LLNL-CODE-644248
#  
#  This file is part of Magpie, scripts for running Hadoop on
#  traditional HPC systems.  For details, see https://github.com/llnl/magpie.
#  
#  Magpie is free software; you can redistribute it and/or modify it
#  under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  Magpie is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with Magpie.  If not, see <http://www.gnu.org/licenses/>.
#############################################################################

# This script is for interactive mode.  For the most part, it
# shouldn't be editted.  See job submission files for configuration
# details.

source ${MAGPIE_SCRIPTS_HOME}/magpie-common-exports
source ${MAGPIE_SCRIPTS_HOME}/magpie-common-functions
source ${MAGPIE_SCRIPTS_HOME}/magpie-variable-conversion

# For this run, we will use cluster specific paths
Magpie_make_all_local_dirs_node_specific

mypid=$$

${MAGPIE_SCRIPTS_HOME}/magpie-run-sleep &
childpid=$!


# Some systems have SIGUSR1 as USR1 so we hardcode the value of 10

echo "*******************************************************"
echo "* Run '${MAGPIE_REMOTE_CMD:-ssh}${MAGPIE_REMOTE_CMD_OPTS:+" "}${MAGPIE_REMOTE_CMD_OPTS} $(hostname) kill -s 10 ${mypid}' to exit 'interactive' mode early."
echo "*******************************************************"

trap "echo \"Received interrupt from user, interactive mode ending early.\"; kill -s 9 ${childpid}" 10

wait $childpid

childstatus=$?

if [ "${childstatus}" == "0" ]
then
    echo "*******************************************************"
    echo "* End of interactive mode"
    echo "*******************************************************"
fi
