#!/bin/bash
#############################################################################
#  Copyright (C) 2013-2015 Lawrence Livermore National Security, LLC.
#  Produced at Lawrence Livermore National Laboratory (cf, DISCLAIMER).
#  Written by Albert Chu <chu11@llnl.gov>
#  LLNL-CODE-644248
#  
#  This file is part of Magpie, scripts for running Hadoop on
#  traditional HPC systems.  For details, see https://github.com/llnl/magpie.
#  
#  Magpie is free software; you can redistribute it and/or modify it
#  under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  Magpie is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with Magpie.  If not, see <http://www.gnu.org/licenses/>.
#############################################################################

# This is used by scripts, don't edit this
#
# This file has common hadoop filesystem path calculations.  Should be
# sourced and used only after magpie-setup-core is run b/c it depends
# on master/slaves to be setup and magpie-exports-user to be callable.

source ${MAGPIE_SCRIPTS_HOME}/magpie-defaults
source ${MAGPIE_SCRIPTS_HOME}/magpie-exports-submission-type
source ${MAGPIE_SCRIPTS_HOME}/magpie-exports-user
source ${MAGPIE_SCRIPTS_HOME}/magpie-lib-hdfs
source ${MAGPIE_SCRIPTS_HOME}/magpie-lib-log

# XXX deal with viewfs & federation
Magpie_calculate_hadoop_filesystem_paths () {
    local noderank=$1
    if [ "${HADOOP_FILESYSTEM_MODE}" == "hdfs" ]
    then
        hadooptmpdir=`echo ${HADOOP_HDFS_PATH} | awk -F, '{print $1}'`
        if Magpie_hdfs_federation_enabled
        then
            fsdefault="viewfs:///"
        else
            fsdefault="hdfs://${HADOOP_MASTER_NODE}:${default_hadoop_hdfs_namenode_address}"
        fi
    elif [ "${HADOOP_FILESYSTEM_MODE}" == "hdfsoverlustre" ]
    then
        if [ "${HADOOP_PER_JOB_HDFS_PATH}" == "yes" ]
        then
            hadooptmpdir="${HADOOP_HDFSOVERLUSTRE_PATH}/${MAGPIE_JOB_ID}/node-${noderank}"
        else
            hadooptmpdir="${HADOOP_HDFSOVERLUSTRE_PATH}/node-${noderank}"
        fi
        if Magpie_hdfs_federation_enabled
        then
            fsdefault="viewfs:///"
        else
            fsdefault="hdfs://${HADOOP_MASTER_NODE}:${default_hadoop_hdfs_namenode_address}"
        fi
    elif [ "${HADOOP_FILESYSTEM_MODE}" == "hdfsovernetworkfs" ]
    then
        if [ "${HADOOP_PER_JOB_HDFS_PATH}" == "yes" ]
        then
            hadooptmpdir="${HADOOP_HDFSOVERNETWORKFS_PATH}/${MAGPIE_JOB_ID}/node-${noderank}"
        else
            hadooptmpdir="${HADOOP_HDFSOVERNETWORKFS_PATH}/node-${noderank}"
        fi
        
        if Magpie_hdfs_federation_enabled
        then
            fsdefault="viewfs:///"
        else
            fsdefault="hdfs://${HADOOP_MASTER_NODE}:${default_hadoop_hdfs_namenode_address}"
        fi
    elif [ "${HADOOP_FILESYSTEM_MODE}" == "rawnetworkfs" ]
    then
        if [ "${HADOOP_PER_JOB_HDFS_PATH}" == "yes" ]
        then
            hadooptmpdir="${HADOOP_RAWNETWORKFS_PATH}/${MAGPIE_JOB_ID}/node-${noderank}"
        else
            hadooptmpdir="${HADOOP_RAWNETWORKFS_PATH}/node-${noderank}"
        fi
        fsdefault="file:///"
    elif [ "${HADOOP_FILESYSTEM_MODE}" == "intellustre" ]
    then
        if [ "${HADOOP_PER_JOB_HDFS_PATH}" == "yes" ]
        then
            hadooptmpdir="${HADOOP_INTELLUSTRE_PATH}/${MAGPIE_JOB_ID}/tmp"
        else
            hadooptmpdir="${HADOOP_INTELLUSTRE_PATH}/tmp"
        fi
        fsdefault="lustre:///"
    elif [ "${HADOOP_FILESYSTEM_MODE}" == "magpienetworkfs" ]
    then
        if [ "${HADOOP_PER_JOB_HDFS_PATH}" == "yes" ]
        then
            hadooptmpdir="${HADOOP_MAGPIENETWORKFS_PATH}/${MAGPIE_JOB_ID}/node-${noderank}"
        else
            hadooptmpdir="${HADOOP_MAGPIENETWORKFS_PATH}/node-${noderank}"
        fi
        fsdefault="magpienetworkfs:///"
    else
        Magpie_output_internal_error "Illegal HADOOP_FILESYSTEM_MODE \"${HADOOP_FILESYSTEM_MODE}\" specified"
        exit 1
    fi
}
