#!/bin/bash
#############################################################################
#  Copyright (C) 2013 Lawrence Livermore National Security, LLC.
#  Produced at Lawrence Livermore National Laboratory (cf, DISCLAIMER).
#  Written by Albert Chu <chu11@llnl.gov>
#  LLNL-CODE-644248
#  
#  This file is part of Magpie, scripts for running Hadoop on
#  traditional HPC systems.  For details, see <URL>.
#  
#  Magpie is free software; you can redistribute it and/or modify it
#  under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  Magpie is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with Magpie.  If not, see <http://www.gnu.org/licenses/>.
#############################################################################

if [ "${MAGPIE_SUBMISSION_TYPE}" == "slurmsbatch" ] \
    || [ "${MAGPIE_SUBMISSION_TYPE}" == "msubslurm" ]
then
    export MAGPIE_CLUSTER_NODERANK="${SLURM_NODEID:=0}"
    export MAGPIE_NODE_COUNT="${SLURM_NNODES}"
    export MAGPIE_NODELIST="${SLURM_JOB_NODELIST}"
    export MAGPIE_JOB_NAME="${SLURM_JOB_NAME}"
    export MAGPIE_JOB_ID="${SLURM_JOB_ID}"
    export MAGPIE_TIMELIMIT_MINUTES="${SBATCH_TIMELIMIT}"
fi
