#!/bin/bash
#############################################################################
#  Copyright (C) 2013-2015 Lawrence Livermore National Security, LLC.
#  Produced at Lawrence Livermore National Laboratory (cf, DISCLAIMER).
#  Written by Albert Chu <chu11@llnl.gov>
#  LLNL-CODE-644248
#  
#  This file is part of Magpie, scripts for running Hadoop on
#  traditional HPC systems.  For details, see https://github.com/llnl/magpie.
#  
#  Magpie is free software; you can redistribute it and/or modify it
#  under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  Magpie is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with Magpie.  If not, see <http://www.gnu.org/licenses/>.
#############################################################################

# This script is for running the tachyon testtachyon sanity test.  For
# the most part, it shouldn't be editted.  See job submission files
# for configuration details.

source ${MAGPIE_SCRIPTS_HOME}/magpie-exports-core

command="${TACHYON_HOME}/${tachyoncmdprefix}/tachyon tfs ls /"
echo "Running $command" >&2
$command

command="${TACHYON_HOME}/${tachyoncmdprefix}/tachyon tfs mkdir /tachyontestdir"
echo "Running $command" >&2
$command

command="${TACHYON_HOME}/${tachyoncmdprefix}/tachyon tfs ls /"
echo "Running $command" >&2
$command

command="${TACHYON_HOME}/${tachyoncmdprefix}/tachyon tfs touch /tachyontestdir/touchedfile"
echo "Running $command" >&2
$command

command="${TACHYON_HOME}/${tachyoncmdprefix}/tachyon tfs ls /tachyontestdir"
echo "Running $command" >&2
$command

command="${TACHYON_HOME}/${tachyoncmdprefix}/tachyon tfs rmr /tachyontestdir"
echo "Running $command" >&2
$command

command="${TACHYON_HOME}/${tachyoncmdprefix}/tachyon tfs ls /"
echo "Running $command" >&2
$command

exit 0
