#!/bin/bash
#############################################################################
#  Copyright (C) 2013 Lawrence Livermore National Security, LLC.
#  Produced at Lawrence Livermore National Laboratory (cf, DISCLAIMER).
#  Written by Albert Chu <chu11@llnl.gov>
#  LLNL-CODE-644248
#  
#  This file is part of Magpie, scripts for running Hadoop on
#  traditional HPC systems.  For details, see <URL>.
#  
#  Magpie is free software; you can redistribute it and/or modify it
#  under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  Magpie is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with Magpie.  If not, see <http://www.gnu.org/licenses/>.
#############################################################################

# This script is for running the 'testall' facility.  For the most
# part, it shouldn't be editted.  See job submission files for
# configuration details.

source ${MAGPIE_SCRIPTS_HOME}/magpie-submission-convert
source ${MAGPIE_SCRIPTS_HOME}/magpie-common-exports
source ${MAGPIE_SCRIPTS_HOME}/magpie-common-functions

if [ "${HADOOP_SETUP}" == "yes" ] \
   && [ "${HADOOP_MODE}" != "setuponly" ] \
   && ([ "${HADOOP_SETUP_TYPE}" == "MR1" ] || [ "${HADOOP_SETUP_TYPE}" == "MR2" ])
then
    echo "*******************************************************"
    echo "* Running Hadoop Terasort"
    echo "*******************************************************"
    (${MAGPIE_SCRIPTS_HOME}/magpie-run-terasort)
fi

if [ "${PIG_SETUP}" == "yes" ]
then
    echo "*******************************************************"
    echo "* Running Pig Testpig"
    echo "*******************************************************"
    (${MAGPIE_SCRIPTS_HOME}/magpie-run-testpig)
fi

if [ "${HBASE_SETUP}" == "yes" ] \
   && [ "${HBASE_MODE}" != "setuponly" ]
then
    echo "*******************************************************"
    echo "* Running Hbase Performance Evaluation"
    echo "*******************************************************"
    (${MAGPIE_SCRIPTS_HOME}/magpie-run-performanceeval)
fi

if [ "${SPARK_SETUP}" == "yes" ] \
   && [ "${SPARK_MODE}" != "setuponly" ]
then
    echo "*******************************************************"
    echo "* Running Spark SparkPi"
    echo "*******************************************************"
    (${MAGPIE_SCRIPTS_HOME}/magpie-run-sparkpi)
fi

if [ "${STORM_SETUP}" == "yes" ] \
   && [ "${STORM_MODE}" != "setuponly" ]
then
    echo "*******************************************************"
    echo "* Running Storm Foobar"
    echo "*******************************************************"
    (${MAGPIE_SCRIPTS_HOME}/magpie-run-stormwordcount)
fi

if [ "${ZOOKEEPER_SETUP}" == "yes" ] \
   && [ "${ZOOKEEPER_MODE}" != "setuponly" ]
then
    echo "*******************************************************"
    echo "* Running Zookeeper Zookeeperruok"
    echo "*******************************************************"
    (${MAGPIE_SCRIPTS_HOME}/magpie-run-zookeeperruok)
fi

exit 0
