#!/bin/bash
#############################################################################
#  Copyright (C) 2013-2015 Lawrence Livermore National Security, LLC.
#  Produced at Lawrence Livermore National Laboratory (cf, DISCLAIMER).
#  Written by Albert Chu <chu11@llnl.gov>
#  LLNL-CODE-644248
#  
#  This file is part of Magpie, scripts for running Hadoop on
#  traditional HPC systems.  For details, see https://github.com/llnl/magpie.
#  
#  Magpie is free software; you can redistribute it and/or modify it
#  under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  Magpie is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with Magpie.  If not, see <http://www.gnu.org/licenses/>.
#############################################################################

# These are functions to be called by magpie-run

source ${MAGPIE_SCRIPTS_HOME}/magpie-constants
source ${MAGPIE_SCRIPTS_HOME}/magpie-exports-submission-type
source ${MAGPIE_SCRIPTS_HOME}/magpie-exports-core
source ${MAGPIE_SCRIPTS_HOME}/magpie-exports-job-dependent
source ${MAGPIE_SCRIPTS_HOME}/magpie-lib-core
source ${MAGPIE_SCRIPTS_HOME}/magpie-lib-job-management
source ${MAGPIE_SCRIPTS_HOME}/magpie-lib-local-dirs-conversion
source ${MAGPIE_SCRIPTS_HOME}/magpie-lib-log

Magpie_run_start_kafka () {
    if [ "${KAFKA_SETUP}" == "yes" ] && [ "${prior_setup_successful}" == "true" ]
    then
        if [ "${zookeeper_setup_successful}" == "0" ]
        then
            Magpie_output_internal_error "Attempt to setup Kafka without Zookeeper being setup"
            kafka_should_be_torndown=0
            kafka_setup_successful=0
            return 1
        fi

        cd ${KAFKA_HOME}

        if [ ${KAFKA_MODE} != "setuponly" ]
        then
            # Make variables unspecified for launching
            Magpie_make_all_local_dirs_unspecified

            echo "Starting Kafka"
            ${MAGPIE_SCRIPTS_HOME}/bin/magpie-kafka-start-all.sh 
            
            Magpie_make_all_local_dirs_node_specific

            # My rough estimate for setup time is 30 seconds per 128 nodes
            local sleepwait=`expr ${KAFKA_SLAVE_COUNT} \/ 128 \* 30`
            if [ ${sleepwait} -lt 30 ]
            then
                sleepwait=30
            fi
            echo "Waiting ${sleepwait} seconds to allow Kafka daemons to setup"
            sleep ${sleepwait}
            totalsleepwait=`expr ${totalsleepwait} + ${sleepwait}`
        fi

        echo "*******************************************************"
        echo "*"
        echo "* Kafka Information"
        echo "*"
        echo "* To access kafka directly, you'll want to:"
        echo "*   ${MAGPIE_REMOTE_CMD:-ssh}${MAGPIE_REMOTE_CMD_OPTS:+" "}${MAGPIE_REMOTE_CMD_OPTS} ${KAFKA_MASTER_NODE}"
        if echo $MAGPIE_SHELL | grep -q csh
        then
            echo "*   setenv KAFKA_CONF_DIR \"${KAFKA_CONF_DIR}\""
        else
            echo "*   export KAFKA_CONF_DIR=\"${KAFKA_CONF_DIR}\""
        fi
        echo "*   cd $KAFKA_HOME"
        echo "*"
        echo "* Then you can do as you please.  To interact with Kafka you can use the applications available in:"
        echo "*" 
        echo "*   ${KAFKA_HOME}/${kafkacmdprefix}"

        echo "*" 
        echo "* Some additional environment variables you may sometimes wish to set"
        echo "*" 
        if echo $MAGPIE_SHELL | grep -q csh
        then
            echo "*   setenv JAVA_HOME \"${JAVA_HOME}\""
            echo "*   setenv KAFKA_HOME \"${KAFKA_HOME}\""
        else
            echo "*   export JAVA_HOME=\"${JAVA_HOME}\""
            echo "*   export KAFKA_HOME=\"${KAFKA_HOME}\""
        fi

        if [ "${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}X" != "X" ]
        then
            echo "*"
            echo "* If running interactively, sourcing"
            echo "*"
            echo "* ${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}"
            echo "*"
            echo "* will set most common environment variables for your job."
        fi
        echo "*" 
        echo "*******************************************************"

        if [ "${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}X" != "X" ]
        then
            if echo $MAGPIE_SHELL | grep -q csh
            then
                echo "setenv KAFKA_HOME \"${KAFKA_HOME}\"" >> ${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}
            else
                echo "export KAFKA_HOME=\"${KAFKA_HOME}\"" >> ${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}
            fi
            echo "" >> ${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}
        fi

        if [ ${KAFKA_MODE} != "setuponly" ]
        then
            local magpiestartuptimeseconds=`expr ${MAGPIE_STARTUP_TIME} \* 60`

            if [ "${totalsleepwait}" -lt "${magpiestartuptimeseconds}" ]
            then  
            # Could be more dynamic w/ slurm call to determine current
            # run time, but probably is sufficient for this trivial
            # part.  Minimally, have to leave the totalsleepwait code
            # around for non-slurm systems.
                local kafkamaxwaitseconds=`expr ${magpiestartuptimeseconds} - ${totalsleepwait}`
                
                if [ "${kafkamaxwaitseconds}" -lt 30 ]
                then
                    kafkamaxwaitseconds=30
                fi
                
                local kafkamaxwaittimes=`expr ${kafkamaxwaitseconds} \/ 30`
            else
                local kafkarmaxwaittimes=1
            fi
            
            cd ${KAFKA_HOME}

            local kafkacameup=0
            
            for i in `seq 1 ${kafkamaxwaittimes}`
            do
                local serverschk=0
                local serversup=0
                for server in `cat ${KAFKA_CONF_DIR}/masters`;
                do
                    serverschk=`expr ${serverschk} + 1`
                    local serverisup=`${MAGPIE_REMOTE_CMD:-ssh} ${MAGPIE_REMOTE_CMD_OPTS} $server ps -ef | grep -c kafka\.Kafka`
                    if [ "${serverisup}" -gt "0" ] ;
                    then 
                        serversup=`expr ${serversup} + 1`
                    fi
                done

                for server in `cat ${KAFKA_CONF_DIR}/slaves`;
                do
                    serverschk=`expr ${serverschk} + 1`
                    local serverisup=`${MAGPIE_REMOTE_CMD:-ssh} ${MAGPIE_REMOTE_CMD_OPTS} $server ps -ef | grep -c kafka\.Kafka`
                    if [ "${serverisup}" -gt "0" ] ;
                    then 
                        serversup=`expr ${serversup} + 1`
                    fi
                done

                echo "$serversup/$serverschk Kafka Servers are up."
                if [ "$serverschk" -eq "$serversup" ]
                then 
                    kafkacameup=1
                    break
                fi

                echo "Waiting 30 more seconds for Kafka Servers to come up"
                sleep 30
                totalsleepwait=`expr ${totalsleepwait} + 30`
            done
            
            if [ "${kafkacameup}" == "0" ]
            then
                echo "Not all Kafka Servers came up, setup problem or maybe need to increase MAGPIE_STARTUP_TIME"
                kafka_should_be_torndown=1
                kafka_setup_successful=0
                prior_setup_successful=false
            else
                kafka_should_be_torndown=1
                kafka_setup_successful=1
            fi
        else
            kafka_should_be_torndown=1
            kafka_setup_successful=1
        fi
    else
        kafka_should_be_torndown=0
        kafka_setup_successful=1
    fi
}

Magpie_run_kafka () {
    if [ "${KAFKA_MODE}" == "performance" ]
    then
        echo "*******************************************************"
        echo "* Running Performance"
        echo "*******************************************************"
        ${MAGPIE_SCRIPTS_HOME}/magpie-run-execute script ${MAGPIE_SCRIPTS_HOME}/magpie-run-job-kafka-performance &
        local scriptpid=$!
        Magpie_wait_script_sigusr2_on_job_timeout ${scriptpid}
    elif [ "${KAFKA_MODE}" == "setuponly" ]
    then
        echo "*******************************************************"
        echo "* Entering Kafka ${KAFKA_MODE} mode"
        echo "*******************************************************"
        ${MAGPIE_SCRIPTS_HOME}/magpie-run-job-sleep countdown &
        local scriptpid=$!
        wait ${scriptpid}
    fi
}

Magpie_run_stop_kafka () {
    if [ "${zookeeper_teardown_complete}" == "1" ]
    then
        Magpie_output_internal_warning "tearing down Kafka after Zookeeper"
    fi

    if [ "${KAFKA_SETUP}" == "yes" ] && [ "${kafka_should_be_torndown}" == "1" ]
    then
        if [ ${KAFKA_MODE} != "setuponly" ]
        then
            cd ${KAFKA_HOME}
            
            # Make variables unspecified for shutdown
            Magpie_make_all_local_dirs_unspecified
            
            echo "Stopping kafka"
            ${MAGPIE_SCRIPTS_HOME}/bin/magpie-kafka-stop-all.sh
            
            # Make variables specific now within Magpie
            Magpie_make_all_local_dirs_node_specific
        fi
    fi
    kafka_teardown_complete=1
}
