#!/bin/bash
#############################################################################
#  Copyright (C) 2013-2015 Lawrence Livermore National Security, LLC.
#  Produced at Lawrence Livermore National Laboratory (cf, DISCLAIMER).
#  Written by Albert Chu <chu11@llnl.gov>
#  LLNL-CODE-644248
#  
#  This file is part of Magpie, scripts for running Hadoop on
#  traditional HPC systems.  For details, see https://github.com/llnl/magpie.
#  
#  Magpie is free software; you can redistribute it and/or modify it
#  under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  Magpie is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with Magpie.  If not, see <http://www.gnu.org/licenses/>.
#############################################################################

# This script is for running the mahout classifywikipedia sanity test.
# For the most part, it shouldn't be editted.  See job submission
# files for configuration details.

source ${MAGPIE_SCRIPTS_HOME}/magpie-constants
source ${MAGPIE_SCRIPTS_HOME}/magpie-exports-dirs
source ${MAGPIE_SCRIPTS_HOME}/magpie-lib-local-dirs-conversion

# For this run, we will use cluster specific paths
Magpie_make_all_local_dirs_node_specific

export MAHOUT_WORK_DIR="${MAHOUT_LOCAL_SCRATCHSPACE_DIR}/mahout"

if [ ! -d "${MAHOUT_WORK_DIR}" ]
then
    mkdir -p ${MAHOUT_WORK_DIR}
    if [ $? -ne 0 ] ; then
        echo "mkdir failed making ${MAHOUT_WORK_DIR}"
        exit 1
    fi
fi

command="${MAHOUT_HOME}/${mahoutexamplesprefix}/${mahoutcmdprefix}/classify-wikipedia.sh"
echo "Running $command" >&2
echo "1" | $command

exit 0
