#!/bin/bash
#############################################################################
#  Copyright (C) 2013-2015 Lawrence Livermore National Security, LLC.
#  Produced at Lawrence Livermore National Laboratory (cf, DISCLAIMER).
#  Written by Albert Chu <chu11@llnl.gov>
#  LLNL-CODE-644248
#  
#  This file is part of Magpie, scripts for running Hadoop on
#  traditional HPC systems.  For details, see https://github.com/llnl/magpie.
#  
#  Magpie is free software; you can redistribute it and/or modify it
#  under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  Magpie is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with Magpie.  If not, see <http://www.gnu.org/licenses/>.
#############################################################################

# This script executes post magpie run cleanup.  For the most part, it
# shouldn't be editted.  See job submission files for configuration
# details.

source ${MAGPIE_SCRIPTS_HOME}/magpie-submission-convert
source ${MAGPIE_SCRIPTS_HOME}/magpie-common-exports
source ${MAGPIE_SCRIPTS_HOME}/magpie-common-functions
source ${MAGPIE_SCRIPTS_HOME}/magpie-helper-functions
source ${MAGPIE_SCRIPTS_HOME}/magpie-variable-conversion

Magpie_make_all_local_dirs_node_specific

myhostname=`hostname`
	    
if [ "${HADOOP_FILESYSTEM_MODE}" == "hdfs" ] \
    && [ "${HADOOP_HDFS_PATH_CLEAR}" == "yes" ]
then
    IFSORIG=${IFS}
    IFS=","
    for hdfspath in ${HADOOP_HDFS_PATH}
    do
	if [ -d "${hdfspath}" ]
	then
	    echo "${myhostname}: Clearing directory ${hdfspath}"
	    rm -rf ${hdfspath}
	fi
    done
    IFS=${IFSORIG}
fi

if [ "${ZOOKEEPER_DATA_DIR_CLEAR}" == "yes" ]
then
    echo "${myhostname}: Clearing directory ${ZOOKEEPER_DATA_DIR}"
    rm -rf ${ZOOKEEPER_DATA_DIR}
fi

exit 0
