#!/bin/bash
#############################################################################
#  Copyright (C) 2013-2015 Lawrence Livermore National Security, LLC.
#  Produced at Lawrence Livermore National Laboratory (cf, DISCLAIMER).
#  Written by Albert Chu <chu11@llnl.gov>
#  LLNL-CODE-644248
#  
#  This file is part of Magpie, scripts for running Hadoop on
#  traditional HPC systems.  For details, see https://github.com/llnl/magpie.
#  
#  Magpie is free software; you can redistribute it and/or modify it
#  under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  Magpie is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with Magpie.  If not, see <http://www.gnu.org/licenses/>.
#############################################################################

# This script is the main setup script.  For the most part, it
# shouldn't be editted.  See job submission files for configuration
# details.

source ${MAGPIE_SCRIPTS_HOME}/magpie-exports-submission-type
source ${MAGPIE_SCRIPTS_HOME}/magpie-common-exports
source ${MAGPIE_SCRIPTS_HOME}/magpie-common-functions

(${MAGPIE_SCRIPTS_HOME}/magpie-setup-core)
if [ $? -ne 0 ] ; then
    exit 1
fi

if [ "${HADOOP_SETUP}" == "yes" ]
then
    (${MAGPIE_SCRIPTS_HOME}/magpie-setup-hadoop)
    if [ $? -ne 0 ] ; then
	exit 1
    fi
fi

if [ "${PIG_SETUP}" == "yes" ]
then
    (${MAGPIE_SCRIPTS_HOME}/magpie-setup-pig)
    if [ $? -ne 0 ] ; then
	exit 1
    fi
fi

if [ "${MAHOUT_SETUP}" == "yes" ]
then
    (${MAGPIE_SCRIPTS_HOME}/magpie-setup-mahout)
    if [ $? -ne 0 ] ; then
	exit 1
    fi
fi

if [ "${HBASE_SETUP}" == "yes" ]
then
    (${MAGPIE_SCRIPTS_HOME}/magpie-setup-hbase)
    if [ $? -ne 0 ] ; then
	exit 1
    fi
fi

if [ "${PHOENIX_SETUP}" == "yes" ]
then
    (${MAGPIE_SCRIPTS_HOME}/magpie-setup-phoenix)
    if [ $? -ne 0 ] ; then
	exit 1
    fi
fi

if [ "${SPARK_SETUP}" == "yes" ]
then
    (${MAGPIE_SCRIPTS_HOME}/magpie-setup-spark)
    if [ $? -ne 0 ] ; then
	exit 1
    fi
fi

if [ "${KAFKA_SETUP}" == "yes" ]
then
    (${MAGPIE_SCRIPTS_HOME}/magpie-setup-kafka)
    if [ $? -ne 0 ] ; then
	exit 1
    fi
fi

if [ "${ZEPPELIN_SETUP}" == "yes" ]
then
    (${MAGPIE_SCRIPTS_HOME}/magpie-setup-zeppelin)
    if [ $? -ne 0 ] ; then
	exit 1
    fi
fi

if [ "${STORM_SETUP}" == "yes" ]
then
    (${MAGPIE_SCRIPTS_HOME}/magpie-setup-storm)
    if [ $? -ne 0 ] ; then
	exit 1
    fi
fi

if [ "${TACHYON_SETUP}" == "yes" ]
then
    (${MAGPIE_SCRIPTS_HOME}/magpie-setup-tachyon)
    if [ $? -ne 0 ] ; then
	exit 1
    fi
fi

if [ "${ZOOKEEPER_SETUP}" == "yes" ]
then
    (${MAGPIE_SCRIPTS_HOME}/magpie-setup-zookeeper)
    if [ $? -ne 0 ] ; then
	exit 1
    fi
fi

exit 0
