#!/bin/bash
#############################################################################
#  Copyright (C) 2013-2015 Lawrence Livermore National Security, LLC.
#  Produced at Lawrence Livermore National Laboratory (cf, DISCLAIMER).
#  Written by Albert Chu <chu11@llnl.gov>
#  LLNL-CODE-644248
#  
#  This file is part of Magpie, scripts for running Hadoop on
#  traditional HPC systems.  For details, see https://github.com/llnl/magpie.
#  
#  Magpie is free software; you can redistribute it and/or modify it
#  under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  Magpie is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with Magpie.  If not, see <http://www.gnu.org/licenses/>.
#############################################################################

# This script is the core processing script for setting up daemons and
# running jobs.  For the most part, it shouldn't be editted.  See
# job submission files for configuration details.

source ${MAGPIE_SCRIPTS_HOME}/magpie-submission-convert
source ${MAGPIE_SCRIPTS_HOME}/magpie-common-exports
source ${MAGPIE_SCRIPTS_HOME}/magpie-common-functions
source ${MAGPIE_SCRIPTS_HOME}/magpie-helper-functions
source ${MAGPIE_SCRIPTS_HOME}/magpie-variable-conversion
source ${MAGPIE_SCRIPTS_HOME}/magpie-generated-exports

Magpie_run_stop_hbase () {
    if [ "${hadoop_teardown_complete}" == "1" ]
    then
	echo "Magpie Internal Warning: tearing down Hbase after Hadoop"
    fi

    if [ "${zookeeper_teardown_complete}" == "1" ]
    then
	echo "Magpie Internal Warning: tearing down Hbase after Zookeeper"
    fi

    if [ "${HBASE_SETUP}" == "yes" ] && [ "${hbase_should_be_torndown}" == "1" ]
    then
	if [ ${HBASE_MODE} != "setuponly" ]
	then
	    cd ${HBASE_HOME}
	    
	    echo "Stopping hbase"
	    
	    if [ "${hbase_setup_successful}" == "1" ]
	    then
		if [ "${HBASE_MAJOR_COMPACTION_ON_SHUTDOWN}X" == "X" ] || [ "${HBASE_MAJOR_COMPACTION_ON_SHUTDOWN}" == "yes" ]
		then
		    echo "Doing major compaction before shutting down ..."
		    
		    local command="echo list"
		    echo "Running $command in hbase shell" >&2
		    local listoutput=`$command | ${hbasecmdprefix}/hbase shell | sed -n '/TABLE/,/seconds/p' | tail -n+2 | head -n -1`
		    
		    for table in ${listoutput}
		    do
			command="echo major_compact '${table}'"
			echo "Running $command in hbase shell" >&2
			$command | ${hbasecmdprefix}/hbase shell
		    done
		fi
	    fi
	    
	    # Make variables unspecified for shutdown
	    Magpie_make_all_local_dirs_unspecified

            if [ "${HBASE_START_THRIFT_SERVER}" == "yes" ]
            then
		${hbasesetupscriptprefix}/hbase-daemon.sh stop thrift
            fi

	    ${hbasesetupscriptprefix}/stop-hbase.sh

            # Make variables specific now within Magpie
	    Magpie_make_all_local_dirs_node_specific
	fi
    fi
    hbase_teardown_complete=1
}