#!/bin/bash
#############################################################################
#  Copyright (C) 2013-2015 Lawrence Livermore National Security, LLC.
#  Produced at Lawrence Livermore National Laboratory (cf, DISCLAIMER).
#  Written by Albert Chu <chu11@llnl.gov>
#  LLNL-CODE-644248
#  
#  This file is part of Magpie, scripts for running Hadoop on
#  traditional HPC systems.  For details, see https://github.com/llnl/magpie.
#  
#  Magpie is free software; you can redistribute it and/or modify it
#  under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  Magpie is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with Magpie.  If not, see <http://www.gnu.org/licenses/>.
#############################################################################

# Export environment variables we promised to export in documentation
# and various variables needed.
#
# Unlke magpie-common-exports, this must only be called before
# magpie-pre-run, magpie-run, and magpie-post-run, as it is dependent
# on the magpie setup.
#
# This is used by scripts, don't edit this

source ${MAGPIE_SCRIPTS_HOME}/magpie-exports-submission-type
source ${MAGPIE_SCRIPTS_HOME}/magpie-variable-conversion
source ${MAGPIE_SCRIPTS_HOME}/magpie-common-exports

# Initially make variables specific to node
Magpie_make_all_local_dirs_node_specific

if [ "${ZOOKEEPER_SETUP}" == "yes" ]
then
    zookeepernodes=`cat ${ZOOKEEPER_CONF_DIR}/zookeeper_slaves`
    zookeepernodesfirst=`echo "${zookeepernodes}" | head -1`

    export ZOOKEEPER_NODES_FIRST="${zookeepernodesfirst}"

    zookeepernodeslist=""
    for zookeepernode in ${zookeepernodes}
    do
	zookeepernodeslist="${zookeepernodeslist}${zookeepernodeslist:+","}${zookeepernode}"
    done

    export ZOOKEEPER_NODES="${zookeepernodeslist}"
fi