#!/bin/bash
#############################################################################
#  Copyright (C) 2013-2015 Lawrence Livermore National Security, LLC.
#  Produced at Lawrence Livermore National Laboratory (cf, DISCLAIMER).
#  Written by Albert Chu <chu11@llnl.gov>
#  LLNL-CODE-644248
#  
#  This file is part of Magpie, scripts for running Hadoop on
#  traditional HPC systems.  For details, see https://github.com/llnl/magpie.
#  
#  Magpie is free software; you can redistribute it and/or modify it
#  under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  Magpie is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with Magpie.  If not, see <http://www.gnu.org/licenses/>.
#############################################################################

# This script is the core sparkpi running script.  For the most part,
# it shouldn't be editted.  See job submission files for configuration
# details.

source ${MAGPIE_SCRIPTS_HOME}/magpie-constants
source ${MAGPIE_SCRIPTS_HOME}/magpie-defaults
source ${MAGPIE_SCRIPTS_HOME}/magpie-exports-dirs
source ${MAGPIE_SCRIPTS_HOME}/magpie-exports-user
source ${MAGPIE_SCRIPTS_HOME}/magpie-lib-local-dirs-conversion

# For this run, we will use cluster specific paths
Magpie_make_all_local_dirs_node_specific

sparkpiclass="org.apache.spark.examples.SparkPi"

if [ "${SPARK_SPARKPI_SLICES}X" != "X" ]
then
    sparkpislices="${SPARK_SPARKPI_SLICES}"
else
    sparkpislices="${SPARK_SLAVE_COUNT}"
fi

cd ${SPARK_HOME}
            
# For some reason in 1.0, the <master> argument was removed.
if echo ${SPARK_VERSION} | grep -q -E "1\.[0-9]\.[0-9]"
then
    # For some reason need to set MASTER environment variable for run-example, makes no sense
    if [ "${SPARK_USE_YARN}" == "yes" ]
    then
        export MASTER="yarn-client"
    else
        # XXX SPARK_MASTER_PORT?
        export MASTER="spark://${SPARK_MASTER_NODE}:${default_spark_master_port}"
    fi
    command="${sparkcmdprefix}/run-example ${sparkpiclass} ${sparkpislices}"
else
    # XXX SPARK_MASTER_PORT?
    command="${sparkcmdprefix}/run-example ${sparkpiclass} spark://$SPARK_MASTER_NODE:$default_spark_master_port ${sparkpislices}"
fi

echo "Running $command" >&2
$command

exit 0
