#!/bin/bash
#############################################################################
#  Copyright (C) 2013-2015 Lawrence Livermore National Security, LLC.
#  Produced at Lawrence Livermore National Laboratory (cf, DISCLAIMER).
#  Written by Albert Chu <chu11@llnl.gov>
#  LLNL-CODE-644248
#  
#  This file is part of Magpie, scripts for running Hadoop on
#  traditional HPC systems.  For details, see https://github.com/llnl/magpie.
#  
#  Magpie is free software; you can redistribute it and/or modify it
#  under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  Magpie is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with Magpie.  If not, see <http://www.gnu.org/licenses/>.
#############################################################################

# Export environment variables we promised to export in documentation
# and various variables needed.
#
# Unlke magpie-exports-core, these exports are dependent on the magpie
# setup.  This should be sourced only after magpie-setup-core has run.
#
# This is used by scripts, don't edit this

source ${MAGPIE_SCRIPTS_HOME}/magpie-defaults
source ${MAGPIE_SCRIPTS_HOME}/magpie-exports-core
source ${MAGPIE_SCRIPTS_HOME}/magpie-lib-local-dirs-conversion
source ${MAGPIE_SCRIPTS_HOME}/magpie-lib-log

# Initially make variables specific to node
Magpie_make_all_local_dirs_node_specific

if [ "${TACHYON_SETUP}" == "yes" ]
then
    if [ ! -f "${TACHYON_CONF_DIR}/masters" ]
    then 
        Magpie_output_internal_error "${TACHYON_CONF_DIR}/masters does not exist"
    fi

    if [ ! -f "${TACHYON_CONF_DIR}/slaves" ]
    then 
        Magpie_output_internal_error "${TACHYON_CONF_DIR}/slaves does not exist"
    fi

    export TACHYON_MASTER_NODE=`head -1 ${TACHYON_CONF_DIR}/masters`
    export TACHYON_MASTER_PORT=${default_tachyon_master_port}
    export TACHYON_SLAVE_COUNT=`cat ${TACHYON_CONF_DIR}/workers|wc -l`
    export TACHYON_FIRST_WORKER_NODE=`head -1 ${TACHYON_CONF_DIR}/workers`
fi

if [ "${ZOOKEEPER_SETUP}" == "yes" ]
then
    if [ ! -f "${ZOOKEEPER_CONF_DIR}/masters" ]
    then 
        Magpie_output_internal_error "${ZOOKEEPER_CONF_DIR}/masters does not exist"
    fi
    
    export ZOOKEEPER_MASTER_NODE=`head -1 ${ZOOKEEPER_CONF_DIR}/masters`

    zookeepernodes=`cat ${ZOOKEEPER_CONF_DIR}/slaves`
    zookeepernodesfirst=`echo "${zookeepernodes}" | head -1`

    export ZOOKEEPER_NODES_FIRST="${zookeepernodesfirst}"

    zookeepernodeslist=""
    for zookeepernode in ${zookeepernodes}
    do
        zookeepernodeslist="${zookeepernodeslist}${zookeepernodeslist:+","}${zookeepernode}"
    done

    export ZOOKEEPER_NODES="${zookeepernodeslist}"
fi
