#!/bin/bash
#############################################################################
#  Copyright (C) 2013 Lawrence Livermore National Security, LLC.
#  Produced at Lawrence Livermore National Laboratory (cf, DISCLAIMER).
#  Written by Albert Chu <chu11@llnl.gov>
#  LLNL-CODE-644248
#  
#  This file is part of Magpie, scripts for running Hadoop on
#  traditional HPC systems.  For details, see <URL>.
#  
#  Magpie is free software; you can redistribute it and/or modify it
#  under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  Magpie is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with Magpie.  If not, see <http://www.gnu.org/licenses/>.
#############################################################################

# This script sets up configuration files for jobs.  For the most
# part, it shouldn't be editted.  See magpie.sbatch for configuration
# details.

#
# Setup a whole bunch of environment variables and directories
# 

mkdir -p $MAGPIE_LOCAL_DIR
if [ $? -ne 0 ] ; then
    echo "mkdir failed making ${MAGPIE_LOCAL_DIR}"
    exit 1
fi

source ${MAGPIE_SCRIPTS_HOME}/magpie-common-exports

#
# Setup Hadoop directories
#

if [ "${HADOOP_SETUP}" == "yes" ]                                                                                                                                                                                 
then  
    mkdir -p $HADOOP_LOCAL_JOB_DIR
    if [ $? -ne 0 ] ; then
	echo "mkdir failed making ${HADOOP_LOCAL_JOB_DIR}"
	exit 1
    fi

    mkdir -p $HADOOP_CONF_DIR
    if [ $? -ne 0 ] ; then
	echo "mkdir failed making ${HADOOP_CONF_DIR}"
	exit 1
    fi

    mkdir -p $HADOOP_LOG_DIR
    if [ $? -ne 0 ] ; then
	echo "mkdir failed making ${HADOOP_LOG_DIR}"
	exit 1
    fi

    export YARN_CONF_DIR=${HADOOP_CONF_DIR}
    export YARN_LOG_DIR=${HADOOP_LOG_DIR}
fi

#
# Setup Zookeeper directories
#

if [ "${ZOOKEEPER_SETUP}" == "yes" ]
then
    mkdir -p $ZOOKEEPER_LOCAL_JOB_DIR
    if [ $? -ne 0 ] ; then
	echo "mkdir failed making ${ZOOKEEPER_LOCAL_JOB_DIR}"
	exit 1
    fi
    
    mkdir -p $ZOOKEEPER_CONF_DIR
    if [ $? -ne 0 ] ; then
	echo "mkdir failed making ${ZOOKEEPER_CONF_DIR}"
	exit 1
    fi

    mkdir -p $ZOOKEEPER_LOG_DIR
    if [ $? -ne 0 ] ; then
	echo "mkdir failed making ${ZOOKEEPER_LOG_DIR}"
	exit 1
    fi
fi

#
# Setup/Calculate Core Master/Slave files
#

hash hostlist 2>/dev/null
if [ $? -eq 0 ]
then
    hostrangescript="hostlist"
    hostrangescriptoptions="-e -d \n"
else
    if [ -x ${MAGPIE_SCRIPTS_HOME}/bin/magpie-expand-nodes ]
    then
	hostrangescript="${MAGPIE_SCRIPTS_HOME}/bin/magpie-expand-nodes"
	hostrangescriptoptions=""
    else
	echo "Cannot find tool to expand host ranges"
	exit 1
    fi
fi

${hostrangescript} ${hostrangescriptoptions} ${SLURM_JOB_NODELIST} | head -1 > ${MAGPIE_LOCAL_DIR}/tmp_masters
${hostrangescript} ${hostrangescriptoptions} ${SLURM_JOB_NODELIST} | tail -n+2 > ${MAGPIE_LOCAL_DIR}/tmp_slaves

if [ "${HADOOP_SETUP}" == "yes" ] && [ "${ZOOKEEPER_SETUP}" == "yes" ]
then
    tmpslavecount=`cat ${MAGPIE_LOCAL_DIR}/tmp_slaves | wc -l`
    hadoopslavecount=`expr ${tmpslavecount} - ${ZOOKEEPER_REPLICATION_COUNT}`
    zookeeperslavestart=`expr ${hadoopslavecount} + 1`

    cp ${MAGPIE_LOCAL_DIR}/tmp_masters ${HADOOP_CONF_DIR}/masters

    if [ "${ZOOKEEPER_SHARE_NODES}" != "yes" ] 
    then
	head -${hadoopslavecount} ${MAGPIE_LOCAL_DIR}/tmp_slaves > ${HADOOP_CONF_DIR}/slaves
    else
	cp ${MAGPIE_LOCAL_DIR}/tmp_slaves ${HADOOP_CONF_DIR}/slaves
    fi

    tail -n+${zookeeperslavestart} ${MAGPIE_LOCAL_DIR}/tmp_slaves > ${ZOOKEEPER_CONF_DIR}/zookeeper_slaves 

elif [ "${HADOOP_SETUP}" == "yes" ] && [ "${ZOOKEEPER_SETUP}" != "yes" ]
then
    cp ${MAGPIE_LOCAL_DIR}/tmp_masters ${HADOOP_CONF_DIR}/masters
    cp ${MAGPIE_LOCAL_DIR}/tmp_slaves ${HADOOP_CONF_DIR}/slaves
else
# [ "${HADOOP_SETUP}" != "yes" ] && [ "${ZOOKEEPER_SETUP}" == "yes" ]
    tmpslavecount=`cat ${MAGPIE_LOCAL_DIR}/tmp_slaves | wc -l`
    hadoopslavecount=`expr ${tmpslavecount} - ${ZOOKEEPER_REPLICATION_COUNT}`
    zookeeperslavestart=`expr ${hadoopslavecount} + 1`

    cp ${MAGPIE_LOCAL_DIR}/tmp_masters ${ZOOKEEPER_CONF_DIR}/masters
    tail -n+${zookeeperslavestart} ${MAGPIE_LOCAL_DIR}/tmp_slaves > ${ZOOKEEPER_CONF_DIR}/zookeeper_slaves 
fi

rm -f ${MAGPIE_LOCAL_DIR}/tmp_masters
rm -f ${MAGPIE_LOCAL_DIR}/tmp_slaves

exit 0
