#!/bin/bash
#############################################################################
#  Copyright (C) 2013-2015 Lawrence Livermore National Security, LLC.
#  Produced at Lawrence Livermore National Laboratory (cf, DISCLAIMER).
#  Written by Albert Chu <chu11@llnl.gov>
#  LLNL-CODE-644248
#  
#  This file is part of Magpie, scripts for running Hadoop on
#  traditional HPC systems.  For details, see https://github.com/llnl/magpie.
#  
#  Magpie is free software; you can redistribute it and/or modify it
#  under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  Magpie is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with Magpie.  If not, see <http://www.gnu.org/licenses/>.
#############################################################################

# This is used by scripts, don't edit this
#
# Export directories promised by user documentation.

source ${MAGPIE_SCRIPTS_HOME}/magpie/exports/magpie-exports-submission-type
source ${MAGPIE_SCRIPTS_HOME}/magpie/lib/magpie-lib-log

# Do not ever "use" the LOCAL_JOB_DIR variables.  They should only be
# referenced when setting SCRATCHSPACE_DIR or CONF_DIR or LOG_DIR variables.

__Magpie_make_magpie_local_dirs () {
    local which=$1

    if [ "${MAGPIE_LOCAL_JOB_DIR}X" == "X" ]
    then
        Magpie_output_internal_error "__Magpie_make_magpie_local_dirs called without MAGPIE_LOCAL_JOB_DIR set"
        exit 1
    fi

    export MAGPIE_LOCAL_CONF_DIR=${MAGPIE_LOCAL_JOB_DIR}/conf
    export MAGPIE_LOCAL_SCRATCHSPACE_DIR=${MAGPIE_LOCAL_JOB_DIR}/scratch

    if [ "${which}" == "specific" ]
    then
        myhostname=`hostname`
        export MAGPIE_LOCAL_CONF_DIR=`echo $MAGPIE_LOCAL_CONF_DIR | sed "s/MAGPIEHOSTNAMESUBSTITUTION/${myhostname}/g"`
        export MAGPIE_LOCAL_SCRATCHSPACE_DIR=`echo $MAGPIE_LOCAL_SCRATCHSPACE_DIR | sed "s/MAGPIEHOSTNAMESUBSTITUTION/${myhostname}/g"`
    fi
}

Magpie_make_magpie_local_dirs_unspecified () {
    __Magpie_make_magpie_local_dirs "generic"
}

Magpie_make_magpie_local_dirs_node_specific () {
    __Magpie_make_magpie_local_dirs "specific"
}

__Magpie_make_hadoop_local_dirs () {
    local which=$1

    if [ "${HADOOP_SETUP}" == "yes" ]
    then
        if [ "${HADOOP_LOCAL_JOB_DIR}X" == "X" ]
        then
            Magpie_output_internal_error "__Magpie_make_hadoop_local_dirs called without HADOOP_LOCAL_JOB_DIR set"
            exit 1
        fi

        export HADOOP_CONF_DIR=${HADOOP_LOCAL_JOB_DIR}/conf
        export HADOOP_LOG_DIR=${HADOOP_LOCAL_JOB_DIR}/log
        export HADOOP_LOCAL_SCRATCHSPACE_DIR=${HADOOP_LOCAL_JOB_DIR}/scratch
        export HADOOP_PID_DIR=${HADOOP_LOCAL_JOB_DIR}/pid

        if [ "${which}" == "specific" ]
        then
            myhostname=`hostname`
            export HADOOP_CONF_DIR=`echo $HADOOP_CONF_DIR | sed "s/MAGPIEHOSTNAMESUBSTITUTION/${myhostname}/g"`
            export HADOOP_LOG_DIR=`echo $HADOOP_LOG_DIR | sed "s/MAGPIEHOSTNAMESUBSTITUTION/${myhostname}/g"`
            export HADOOP_LOCAL_SCRATCHSPACE_DIR=`echo $HADOOP_LOCAL_SCRATCHSPACE_DIR | sed "s/MAGPIEHOSTNAMESUBSTITUTION/${myhostname}/g"`
            export HADOOP_PID_DIR=`echo $HADOOP_PID_DIR | sed "s/MAGPIEHOSTNAMESUBSTITUTION/${myhostname}/g"`
        fi

        # Hadoop 3.0 only wants primary ones, no extra ones
        if echo ${HADOOP_VERSION} | grep -q -E "2\.[0-9]\.[0-9]"
        then
            export YARN_CONF_DIR=${HADOOP_CONF_DIR}
            export YARN_LOG_DIR=${HADOOP_LOG_DIR}
            export YARN_LOCAL_SCRATCHSPACE_DIR=${HADOOP_LOCAL_SCRATCHSPACE_DIR}
            export YARN_PID_DIR=${HADOOP_PID_DIR}
            
            # Hadoop has this completely random other one
            export HADOOP_MAPRED_PID_DIR=${HADOOP_PID_DIR}
        fi
    fi
}

Magpie_make_hadoop_local_dirs_unspecified () {
    __Magpie_make_hadoop_local_dirs "generic"
}

Magpie_make_hadoop_local_dirs_node_specific () {
    __Magpie_make_hadoop_local_dirs "specific"
}

__Magpie_make_pig_local_dirs () {
    local which=$1

    if [ "${PIG_SETUP}" == "yes" ]
    then
        if [ "${PIG_LOCAL_JOB_DIR}X" == "X" ]
        then
            Magpie_output_internal_error "__Magpie_make_pig_local_dirs called without PIG_LOCAL_JOB_DIR set"
            exit 1
        fi

        export PIG_CONF_DIR=${PIG_LOCAL_JOB_DIR}/conf
        export PIG_LOCAL_SCRATCHSPACE_DIR=${PIG_LOCAL_JOB_DIR}/scratch

        if [ "${which}" == "specific" ]
        then
            myhostname=`hostname`
            export PIG_CONF_DIR=`echo $PIG_CONF_DIR | sed "s/MAGPIEHOSTNAMESUBSTITUTION/${myhostname}/g"`
            export PIG_LOCAL_SCRATCHSPACE_DIR=`echo $PIG_LOCAL_SCRATCHSPACE_DIR | sed "s/MAGPIEHOSTNAMESUBSTITUTION/${myhostname}/g"`
        fi
    fi
}

Magpie_make_pig_local_dirs_unspecified () {
    __Magpie_make_pig_local_dirs "generic"
}

Magpie_make_pig_local_dirs_node_specific () {
    __Magpie_make_pig_local_dirs "specific"
}

Magpie_make_mahout_local_dirs () {
    local which=$1

    if [ "${MAHOUT_SETUP}" == "yes" ]
    then
        if [ "${MAHOUT_LOCAL_JOB_DIR}X" == "X" ]
        then
            Magpie_output_internal_error "Magpie_make_mahout_local_dirs called without MAHOUT_LOCAL_JOB_DIR set"
            exit 1
        fi

        export MAHOUT_CONF_DIR=${MAHOUT_LOCAL_JOB_DIR}/conf
        export MAHOUT_LOCAL_SCRATCHSPACE_DIR=${MAHOUT_LOCAL_JOB_DIR}/scratch

        if [ "${which}" == "specific" ]
        then
            myhostname=`hostname`
            export MAHOUT_CONF_DIR=`echo $MAHOUT_CONF_DIR | sed "s/MAGPIEHOSTNAMESUBSTITUTION/${myhostname}/g"`
            export MAHOUT_LOCAL_SCRATCHSPACE_DIR=`echo $MAHOUT_LOCAL_SCRATCHSPACE_DIR | sed "s/MAGPIEHOSTNAMESUBSTITUTION/${myhostname}/g"`
        fi
    fi
}

Magpie_make_mahout_local_dirs_unspecified () {
    Magpie_make_mahout_local_dirs "generic"
}

Magpie_make_mahout_local_dirs_node_specific () {
    Magpie_make_mahout_local_dirs "specific"
}

__Magpie_make_hbase_local_dirs () {
    local which=$1

    if [ "${HBASE_SETUP}" == "yes" ]
    then
        if [ "${HBASE_LOCAL_JOB_DIR}X" == "X" ]
        then
            Magpie_output_internal_error "__Magpie_make_hbase_local_dirs called without HBASE_LOCAL_JOB_DIR set"
            exit 1
        fi

        export HBASE_CONF_DIR=${HBASE_LOCAL_JOB_DIR}/conf
        export HBASE_LOG_DIR=${HBASE_LOCAL_JOB_DIR}/log
        export HBASE_LOCAL_SCRATCHSPACE_DIR=${HBASE_LOCAL_JOB_DIR}/scratch
        export HBASE_PID_DIR=${HBASE_LOCAL_JOB_DIR}/pid

        if [ "${which}" == "specific" ]
        then
            myhostname=`hostname`
            export HBASE_CONF_DIR=`echo $HBASE_CONF_DIR | sed "s/MAGPIEHOSTNAMESUBSTITUTION/${myhostname}/g"`
            export HBASE_LOG_DIR=`echo $HBASE_LOG_DIR | sed "s/MAGPIEHOSTNAMESUBSTITUTION/${myhostname}/g"`    
            export HBASE_LOCAL_SCRATCHSPACE_DIR=`echo $HBASE_LOCAL_SCRATCHSPACE_DIR | sed "s/MAGPIEHOSTNAMESUBSTITUTION/${myhostname}/g"`
            export HBASE_PID_DIR=`echo $HBASE_PID_DIR | sed "s/MAGPIEHOSTNAMESUBSTITUTION/${myhostname}/g"`
        fi
    fi
}

Magpie_make_hbase_local_dirs_unspecified () {
    __Magpie_make_hbase_local_dirs "generic"
}

Magpie_make_hbase_local_dirs_node_specific () {
    __Magpie_make_hbase_local_dirs "specific"
}

__Magpie_make_phoenix_local_dirs () {
    local which=$1

    if [ "${PHOENIX_SETUP}" == "yes" ]
    then
        if [ "${PHOENIX_LOCAL_JOB_DIR}X" == "X" ]
        then
            Magpie_output_internal_error "__Magpie_make_phoenix_local_dirs called without PHOENIX_LOCAL_JOB_DIR set"
            exit 1
        fi

        export PHOENIX_CONF_DIR=${PHOENIX_LOCAL_JOB_DIR}/conf
        export PHOENIX_LOG_DIR=${PHOENIX_LOCAL_JOB_DIR}/log
        export PHOENIX_LOCAL_SCRATCHSPACE_DIR=${PHOENIX_LOCAL_JOB_DIR}/scratch
        export PHOENIX_PID_DIR=${PHOENIX_LOCAL_JOB_DIR}/pid

        if [ "${which}" == "specific" ]
        then
            myhostname=`hostname`
            export PHOENIX_CONF_DIR=`echo $PHOENIX_CONF_DIR | sed "s/MAGPIEHOSTNAMESUBSTITUTION/${myhostname}/g"`
            export PHOENIX_LOG_DIR=`echo $PHOENIX_LOG_DIR | sed "s/MAGPIEHOSTNAMESUBSTITUTION/${myhostname}/g"`        
            export PHOENIX_LOCAL_SCRATCHSPACE_DIR=`echo $PHOENIX_LOCAL_SCRATCHSPACE_DIR | sed "s/MAGPIEHOSTNAMESUBSTITUTION/${myhostname}/g"`
            export PHOENIX_PID_DIR=`echo $PHOENIX_PID_DIR | sed "s/MAGPIEHOSTNAMESUBSTITUTION/${myhostname}/g"`
        fi
    fi
}

Magpie_make_phoenix_local_dirs_unspecified () {
    __Magpie_make_phoenix_local_dirs "generic"
}

Magpie_make_phoenix_local_dirs_node_specific () {
    __Magpie_make_phoenix_local_dirs "specific"
}

__Magpie_make_spark_local_dirs () {
    local which=$1

    if [ "${SPARK_SETUP}" == "yes" ]
    then
        if [ "${SPARK_LOCAL_JOB_DIR}X" == "X" ]
        then
            Magpie_output_internal_error "__Magpie_make_spark_local_dirs called without SPARK_LOCAL_JOB_DIR set"
            exit 1
        fi

        export SPARK_CONF_DIR=${SPARK_LOCAL_JOB_DIR}/conf
        export SPARK_LOG_DIR=${SPARK_LOCAL_JOB_DIR}/log
        export SPARK_LOCAL_SCRATCHSPACE_DIR=${SPARK_LOCAL_JOB_DIR}/scratch
        export SPARK_PID_DIR=${SPARK_LOCAL_JOB_DIR}/pid

        if [ "${which}" == "specific" ]
        then
            myhostname=`hostname`
            export SPARK_CONF_DIR=`echo $SPARK_CONF_DIR | sed "s/MAGPIEHOSTNAMESUBSTITUTION/${myhostname}/g"`
            export SPARK_LOG_DIR=`echo $SPARK_LOG_DIR | sed "s/MAGPIEHOSTNAMESUBSTITUTION/${myhostname}/g"`
            export SPARK_LOCAL_SCRATCHSPACE_DIR=`echo $SPARK_LOCAL_SCRATCHSPACE_DIR | sed "s/MAGPIEHOSTNAMESUBSTITUTION/${myhostname}/g"`
            export SPARK_PID_DIR=`echo $SPARK_PID_DIR | sed "s/MAGPIEHOSTNAMESUBSTITUTION/${myhostname}/g"`
        fi
    fi
}

Magpie_make_spark_local_dirs_unspecified () {
    __Magpie_make_spark_local_dirs "generic"
}

Magpie_make_spark_local_dirs_node_specific () {
    __Magpie_make_spark_local_dirs "specific"
}

__Magpie_make_kafka_local_dirs () {
    local which=$1

    if [ "${KAFKA_SETUP}" == "yes" ]
    then
        if [ "${KAFKA_LOCAL_JOB_DIR}X" == "X" ]
        then
            Magpie_output_internal_error "__Magpie_make_kafka_local_dirs called without KAFKA_LOCAL_JOB_DIR set"
            exit 1
        fi

        export KAFKA_CONF_DIR=${KAFKA_LOCAL_JOB_DIR}/conf
        export KAFKA_LOG_DIR=${KAFKA_LOCAL_JOB_DIR}/log
        export KAFKA_LOCAL_SCRATCHSPACE_DIR=${KAFKA_LOCAL_JOB_DIR}/scratch
        export KAFKA_PID_DIR=${KAFKA_LOCAL_JOB_DIR}/pid

        if [ "${which}" == "specific" ]
        then
            myhostname=`hostname`
            export KAFKA_CONF_DIR=`echo $KAFKA_CONF_DIR | sed "s/MAGPIEHOSTNAMESUBSTITUTION/${myhostname}/g"`
            export KAFKA_LOG_DIR=`echo $KAFKA_LOG_DIR | sed "s/MAGPIEHOSTNAMESUBSTITUTION/${myhostname}/g"`
            export KAFKA_LOCAL_SCRATCHSPACE_DIR=`echo $KAFKA_LOCAL_SCRATCHSPACE_DIR | sed "s/MAGPIEHOSTNAMESUBSTITUTION/${myhostname}/g"`
            export KAFKA_PID_DIR=`echo $KAFKA_PID_DIR | sed "s/MAGPIEHOSTNAMESUBSTITUTION/${myhostname}/g"`
        fi
    fi
}

Magpie_make_kafka_local_dirs_unspecified () {
    __Magpie_make_kafka_local_dirs "generic"
}

Magpie_make_kafka_local_dirs_node_specific () {
    __Magpie_make_kafka_local_dirs "specific"
}

Magpie_make_zeppelin_local_dirs () {
    local which=$1

    if [ "${ZEPPELIN_SETUP}" == "yes" ]
    then
        if [ "${ZEPPELIN_LOCAL_JOB_DIR}X" == "X" ]
        then
            Magpie_output_internal_error "Magpie_make_zeppelin_local_dirs called without ZEPPELIN_LOCAL_JOB_DIR set"
            exit 1
        fi

        export ZEPPELIN_CONF_DIR=${ZEPPELIN_LOCAL_JOB_DIR}/conf
        export ZEPPELIN_LOG_DIR=${ZEPPELIN_LOCAL_JOB_DIR}/log
        export ZEPPELIN_LOCAL_SCRATCHSPACE_DIR=${ZEPPELIN_LOCAL_JOB_DIR}/scratch
        export ZEPPELIN_PID_DIR=${ZEPPELIN_LOCAL_JOB_DIR}/pid

        if [ "${which}" == "specific" ]
        then
            myhostname=`hostname`
            export ZEPPELIN_CONF_DIR=`echo $ZEPPELIN_CONF_DIR | sed "s/MAGPIEHOSTNAMESUBSTITUTION/${myhostname}/g"`
            export ZEPPELIN_LOG_DIR=`echo $ZEPPELIN_LOG_DIR | sed "s/MAGPIEHOSTNAMESUBSTITUTION/${myhostname}/g"`
            export ZEPPELIN_LOCAL_SCRATCHSPACE_DIR=`echo $ZEPPELIN_LOCAL_SCRATCHSPACE_DIR | sed "s/MAGPIEHOSTNAMESUBSTITUTION/${myhostname}/g"`
            export ZEPPELIN_PID_DIR=`echo $ZEPPELIN_PID_DIR | sed "s/MAGPIEHOSTNAMESUBSTITUTION/${myhostname}/g"`
        fi
    fi
}

Magpie_make_zeppelin_local_dirs_unspecified () {
    Magpie_make_zeppelin_local_dirs "generic"
}

Magpie_make_zeppelin_local_dirs_node_specific () {
    Magpie_make_zeppelin_local_dirs "specific"
}

__Magpie_make_storm_local_dirs () {
    local which=$1

    if [ "${STORM_SETUP}" == "yes" ]
    then
        if [ "${STORM_LOCAL_JOB_DIR}X" == "X" ]
        then
            Magpie_output_internal_error "__Magpie_make_storm_local_dirs called without STORM_LOCAL_JOB_DIR set"
            exit 1
        fi

        export STORM_CONF_DIR=${STORM_LOCAL_JOB_DIR}/conf
        export STORM_LOG_DIR=${STORM_LOCAL_JOB_DIR}/log
        export STORM_LOCAL_SCRATCHSPACE_DIR=${STORM_LOCAL_JOB_DIR}/scratch

        if [ "${which}" == "specific" ]
        then
            myhostname=`hostname`
            export STORM_CONF_DIR=`echo $STORM_CONF_DIR | sed "s/MAGPIEHOSTNAMESUBSTITUTION/${myhostname}/g"`
            export STORM_LOG_DIR=`echo $STORM_LOG_DIR | sed "s/MAGPIEHOSTNAMESUBSTITUTION/${myhostname}/g"`
            export STORM_LOCAL_SCRATCHSPACE_DIR=`echo $STORM_LOCAL_SCRATCHSPACE_DIR | sed "s/MAGPIEHOSTNAMESUBSTITUTION/${myhostname}/g"`
        fi
    fi
}

Magpie_make_storm_local_dirs_unspecified () {
    __Magpie_make_storm_local_dirs "generic"
}

Magpie_make_storm_local_dirs_node_specific () {
    __Magpie_make_storm_local_dirs "specific"
}

__Magpie_make_zookeeper_local_dirs () {
    local which=$1

    if [ "${ZOOKEEPER_SETUP}" == "yes" ]
    then
        if [ "${ZOOKEEPER_LOCAL_JOB_DIR}X" == "X" ]
        then
            Magpie_output_internal_error "__Magpie_make_zookeeper_local_dirs called without ZOOKEEPER_LOCAL_JOB_DIR set"
            exit 1
        fi

        export ZOOKEEPER_CONF_DIR=${ZOOKEEPER_LOCAL_JOB_DIR}/conf
        export ZOOKEEPER_LOG_DIR=${ZOOKEEPER_LOCAL_JOB_DIR}/log
        export ZOOKEEPER_LOCAL_SCRATCHSPACE_DIR=${ZOOKEEPER_LOCAL_JOB_DIR}/scratch

        if [ "${which}" == "specific" ]
        then
            myhostname=`hostname`
            export ZOOKEEPER_CONF_DIR=`echo $ZOOKEEPER_CONF_DIR | sed "s/MAGPIEHOSTNAMESUBSTITUTION/${myhostname}/g"`
            export ZOOKEEPER_LOG_DIR=`echo $ZOOKEEPER_LOG_DIR | sed "s/MAGPIEHOSTNAMESUBSTITUTION/${myhostname}/g"`
            export ZOOKEEPER_LOCAL_SCRATCHSPACE_DIR=`echo $ZOOKEEPER_LOCAL_SCRATCHSPACE_DIR | sed "s/MAGPIEHOSTNAMESUBSTITUTION/${myhostname}/g"`
        fi
    fi
}

Magpie_make_zookeeper_local_dirs_unspecified () {
    __Magpie_make_zookeeper_local_dirs "generic"
}

Magpie_make_zookeeper_local_dirs_node_specific () {
    __Magpie_make_zookeeper_local_dirs "specific"
}

__Magpie_make_all_local_dirs () {
    __Magpie_make_magpie_local_dirs $1
    __Magpie_make_hadoop_local_dirs $1
    __Magpie_make_pig_local_dirs $1
    __Magpie_make_hbase_local_dirs $1
    __Magpie_make_phoenix_local_dirs $1
    __Magpie_make_spark_local_dirs $1
    __Magpie_make_kafka_local_dirs $1
    __Magpie_make_storm_local_dirs $1
    __Magpie_make_zookeeper_local_dirs $1
}

Magpie_make_all_local_dirs_unspecified () {
    __Magpie_make_all_local_dirs "generic"
}

Magpie_make_all_local_dirs_node_specific () {
    __Magpie_make_all_local_dirs "specific"
}

if [ "${MAGPIE_NO_LOCAL_DIR}" == "yes" ]
then
    export MAGPIE_LOCAL_JOB_DIR=${MAGPIE_LOCAL_DIR}/MAGPIEHOSTNAMESUBSTITUTION/${MAGPIE_JOB_NAME}/${MAGPIE_JOB_ID}
else
    export MAGPIE_LOCAL_JOB_DIR=${MAGPIE_LOCAL_DIR}/${MAGPIE_JOB_NAME}/${MAGPIE_JOB_ID}
fi

# MAGPIE_LOCAL_SCRATCHSPACE_DIR & MAGPIE_LOCAL_CONF_DIR set
Magpie_make_magpie_local_dirs_node_specific

if [ "${HADOOP_SETUP}" == "yes" ]
then
    if [ "${MAGPIE_NO_LOCAL_DIR}" == "yes" ]
    then
        export HADOOP_LOCAL_JOB_DIR=${HADOOP_LOCAL_DIR}/MAGPIEHOSTNAMESUBSTITUTION/${MAGPIE_JOB_NAME}/${MAGPIE_JOB_ID}
    else
        export HADOOP_LOCAL_JOB_DIR=${HADOOP_LOCAL_DIR}/${MAGPIE_JOB_NAME}/${MAGPIE_JOB_ID}
    fi
    # HADOOP_LOCAL_SCRATCHSPACE_DIR & HADOOP_CONF_DIR & HADOOP_LOG_DIR set
    # YARN_LOCAL_SCRATCHSPACE_DIR & YARN_CONF_DIR & YARN_LOG_DIR set
    Magpie_make_hadoop_local_dirs_node_specific
fi

if [ "${PIG_SETUP}" == "yes" ]
then
    if [ "${MAGPIE_NO_LOCAL_DIR}" == "yes" ]
    then
        export PIG_LOCAL_JOB_DIR=${PIG_LOCAL_DIR}/MAGPIEHOSTNAMESUBSTITUTION/${MAGPIE_JOB_NAME}/${MAGPIE_JOB_ID}
    else
        export PIG_LOCAL_JOB_DIR=${PIG_LOCAL_DIR}/${MAGPIE_JOB_NAME}/${MAGPIE_JOB_ID}
    fi
    # PIG_LOCAL_SCRATCHSPACE_DIR & PIG_CONF_DIR set
    Magpie_make_pig_local_dirs_node_specific
fi

if [ "${MAHOUT_SETUP}" == "yes" ]
then
    if [ "${MAGPIE_NO_LOCAL_DIR}" == "yes" ]
    then
        export MAHOUT_LOCAL_JOB_DIR=${MAHOUT_LOCAL_DIR}/MAGPIEHOSTNAMESUBSTITUTION/${MAGPIE_JOB_NAME}/${MAGPIE_JOB_ID}
    else
        export MAHOUT_LOCAL_JOB_DIR=${MAHOUT_LOCAL_DIR}/${MAGPIE_JOB_NAME}/${MAGPIE_JOB_ID}
    fi
    # MAHOUT_LOCAL_SCRATCHSPACE_DIR & MAHOUT_CONF_DIR set
    Magpie_make_mahout_local_dirs_node_specific
fi

if [ "${HBASE_SETUP}" == "yes" ]
then
    if [ "${MAGPIE_NO_LOCAL_DIR}" == "yes" ]
    then
        export HBASE_LOCAL_JOB_DIR=${HBASE_LOCAL_DIR}/MAGPIEHOSTNAMESUBSTITUTION/${MAGPIE_JOB_NAME}/${MAGPIE_JOB_ID}
    else
        export HBASE_LOCAL_JOB_DIR=${HBASE_LOCAL_DIR}/${MAGPIE_JOB_NAME}/${MAGPIE_JOB_ID}
    fi
    # HBASE_LOCAL_SCRATCHSPACE_DIR & HBASE_CONF_DIR & HBASE_LOG_DIR set
    Magpie_make_hbase_local_dirs_node_specific
fi

if [ "${PHOENIX_SETUP}" == "yes" ]
then
    if [ "${MAGPIE_NO_LOCAL_DIR}" == "yes" ]
    then
        export PHOENIX_LOCAL_JOB_DIR=${PHOENIX_LOCAL_DIR}/MAGPIEHOSTNAMESUBSTITUTION/${MAGPIE_JOB_NAME}/${MAGPIE_JOB_ID}
    else
        export PHOENIX_LOCAL_JOB_DIR=${PHOENIX_LOCAL_DIR}/${MAGPIE_JOB_NAME}/${MAGPIE_JOB_ID}
    fi
    # PHOENIX_LOCAL_SCRATCHSPACE_DIR & PHOENIX_CONF_DIR & PHOENIX_LOG_DIR set
    Magpie_make_phoenix_local_dirs_node_specific
fi

if [ "${SPARK_SETUP}" == "yes" ]
then
    if [ "${MAGPIE_NO_LOCAL_DIR}" == "yes" ]
    then
        export SPARK_LOCAL_JOB_DIR=${SPARK_LOCAL_DIR}/MAGPIEHOSTNAMESUBSTITUTION/${MAGPIE_JOB_NAME}/${MAGPIE_JOB_ID}
    else
        export SPARK_LOCAL_JOB_DIR=${SPARK_LOCAL_DIR}/${MAGPIE_JOB_NAME}/${MAGPIE_JOB_ID}
    fi
    # SPARK_LOCAL_SCRATCHSPACE_DIR & SPARK_CONF_DIR & SPARK_LOG_DIR set
    Magpie_make_spark_local_dirs_node_specific
fi

if [ "${KAFKA_SETUP}" == "yes" ]
then
    if [ "${MAGPIE_NO_LOCAL_DIR}" == "yes" ]
    then
        export KAFKA_LOCAL_JOB_DIR=${KAFKA_LOCAL_DIR}/MAGPIEHOSTNAMESUBSTITUTION/${MAGPIE_JOB_NAME}/${MAGPIE_JOB_ID}
    else
        export KAFKA_LOCAL_JOB_DIR=${KAFKA_LOCAL_DIR}/${MAGPIE_JOB_NAME}/${MAGPIE_JOB_ID}
    fi
    # KAFKA_LOCAL_SCRATCHSPACE_DIR & KAFKA_CONF_DIR & KAFKA_LOG_DIR set
    Magpie_make_kafka_local_dirs_node_specific
fi

if [ "${ZEPPELIN_SETUP}" == "yes" ]
then
    if [ "${MAGPIE_NO_LOCAL_DIR}" == "yes" ]
    then
        export ZEPPELIN_LOCAL_JOB_DIR=${ZEPPELIN_LOCAL_DIR}/MAGPIEHOSTNAMESUBSTITUTION/${MAGPIE_JOB_NAME}/${MAGPIE_JOB_ID}
    else
        export ZEPPELIN_LOCAL_JOB_DIR=${ZEPPELIN_LOCAL_DIR}/${MAGPIE_JOB_NAME}/${MAGPIE_JOB_ID}
    fi
    # ZEPPELIN_LOCAL_SCRATCHSPACE_DIR & ZEPPELIN_CONF_DIR & ZEPPELIN_LOG_DIR set
    Magpie_make_zeppelin_local_dirs_node_specific
fi

if [ "${STORM_SETUP}" == "yes" ]
then
    if [ "${MAGPIE_NO_LOCAL_DIR}" == "yes" ]
    then
        export STORM_LOCAL_JOB_DIR=${STORM_LOCAL_DIR}/MAGPIEHOSTNAMESUBSTITUTION/${MAGPIE_JOB_NAME}/${MAGPIE_JOB_ID}
    else
        export STORM_LOCAL_JOB_DIR=${STORM_LOCAL_DIR}/${MAGPIE_JOB_NAME}/${MAGPIE_JOB_ID}
    fi
    # STORM_LOCAL_SCRATCHSPACE_DIR & STORM_CONF_DIR & STORM_LOG_DIR set
    Magpie_make_storm_local_dirs_node_specific
fi

if [ "${ZOOKEEPER_SETUP}" == "yes" ]
then
    if [ "${MAGPIE_NO_LOCAL_DIR}" == "yes" ]
    then
        export ZOOKEEPER_LOCAL_JOB_DIR=${ZOOKEEPER_LOCAL_DIR}/MAGPIEHOSTNAMESUBSTITUTION/${MAGPIE_JOB_NAME}/${MAGPIE_JOB_ID}
    else
        export ZOOKEEPER_LOCAL_JOB_DIR=${ZOOKEEPER_LOCAL_DIR}/${MAGPIE_JOB_NAME}/${MAGPIE_JOB_ID}
    fi
    # ZOOKEEPER_LOCAL_SCRATCHSPACE_DIR & ZOOKEEPER_CONF_DIR & ZOOKEEPER_LOG_DIR set
    Magpie_make_zookeeper_local_dirs_node_specific
fi

