#!/bin/bash
#############################################################################
#  Copyright (C) 2013-2015 Lawrence Livermore National Security, LLC.
#  Produced at Lawrence Livermore National Laboratory (cf, DISCLAIMER).
#  Written by Albert Chu <chu11@llnl.gov>
#  LLNL-CODE-644248
#
#  This file is part of Magpie, scripts for running Hadoop on
#  traditional HPC systems.  For details, see https://github.com/llnl/magpie.
#
#  Magpie is free software; you can redistribute it and/or modify it
#  under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  Magpie is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with Magpie.  If not, see <http://www.gnu.org/licenses/>.
#############################################################################

# Various path constants that we want set
#
# This is used by scripts, don't edit this

if [ "${HADOOP_SETUP}" == "yes" ]
then
    hadoopsetupscriptprefix="sbin"
    hadoopcmdprefix="bin"
    dfsadminscript="hdfs"
fi

if [ "${PIG_SETUP}" == "yes" ]
then
    pigcmdprefix="bin"
fi

if [ "${MAHOUT_SETUP}" == "yes" ]
then
    mahoutexamplesprefix="examples"
    mahoutcmdprefix="bin"
fi

if [ "${HBASE_SETUP}" == "yes" ]
then
    hbasesetupscriptprefix="bin"
    hbasecmdprefix="bin"
fi

if [ "${PHOENIX_SETUP}" == "yes" ]
then
    phoenixcmdprefix="bin"
fi

if [ "${SPARK_SETUP}" == "yes" ]
then
    sparksetupscriptprefix="sbin"
    sparkcmdprefix="bin"
fi

if [ "${KAFKA_SETUP}" == "yes" ]
then
    kafkacmdprefix="bin"
fi

if [ "${ZEPPELIN_SETUP}" == "yes" ]
then
    zeppelincmdprefix="bin"
fi

if [ "${STORM_SETUP}" == "yes" ]
then
    stormcmdprefix="bin"
fi

if [ "${ZOOKEEPER_SETUP}" == "yes" ]
then
    zookeepercmdprefix="bin"
fi
