#!/bin/bash
#############################################################################
#  Copyright (C) 2013-2015 Lawrence Livermore National Security, LLC.
#  Produced at Lawrence Livermore National Laboratory (cf, DISCLAIMER).
#  Written by Albert Chu <chu11@llnl.gov>
#  LLNL-CODE-644248
#
#  This file is part of Magpie, scripts for running Hadoop on
#  traditional HPC systems.  For details, see https://github.com/llnl/magpie.
#
#  Magpie is free software; you can redistribute it and/or modify it
#  under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  Magpie is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with Magpie.  If not, see <http://www.gnu.org/licenses/>.
#############################################################################

# Various constants that we want set
#
# This is used by scripts, don't edit this

source ${MAGPIE_SCRIPTS_HOME}/magpie/lib/magpie-lib-defaults

if [ "${MAGPIE_STARTUP_TIME}X" != "X" ]
then
    magpie_startup_time_value=${MAGPIE_STARTUP_TIME}
else
    magpie_startup_time_value=${default_startup_time}
fi

if [ "${MAGPIE_SHUTDOWN_TIME}X" != "X" ]
then
    magpie_shutdown_time_value=${MAGPIE_SHUTDOWN_TIME}
else
    magpie_shutdown_time_value=${default_shutdown_time}
fi
