#!/bin/bash
#############################################################################
#  Copyright (C) 2013-2015 Lawrence Livermore National Security, LLC.
#  Produced at Lawrence Livermore National Laboratory (cf, DISCLAIMER).
#  Written by Albert Chu <chu11@llnl.gov>
#  LLNL-CODE-644248
#
#  This file is part of Magpie, scripts for running Hadoop on
#  traditional HPC systems.  For details, see https://github.com/llnl/magpie.
#
#  Magpie is free software; you can redistribute it and/or modify it
#  under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  Magpie is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with Magpie.  If not, see <http://www.gnu.org/licenses/>.
#############################################################################

# This is used by scripts, don't edit this
#
# This file has common version number helper functions, does not assume anything setup yet

Magpie_get_spark_major_minor_version() {
    local sparkversion=$1

    # Remove lingering "-bin-hadoop2.4" and similar text"

    local sparkcoreversion=`echo ${sparkversion} | cut -f1 -d"-"`

    # Get only the major and minor version, we don't care about the release

    local sparkmajor=`echo $sparkcoreversion | cut -d. -f1`
    local sparkminor=`echo $sparkcoreversion | cut -d. -f2`

    magpie_sparkmajorminorversion="$sparkmajor.$sparkminor"
}

Magpie_get_spark_major_minor_patch_version() {
    local sparkversion=$1

    # Remove lingering "-bin-hadoop2.4" and similar text"

    local sparkcoreversion=`echo ${sparkversion} | cut -f1 -d"-"`

    magpie_sparkmajorminorpatchversion="$sparkcoreversion"
}

Magpie_get_phoenix_major_minor_version() {
    local phoenixversion=$1

    # Get only the major and minor version, we don't care about the release
    phoenixmajor=`echo ${phoenixversion} | cut -d. -f1`
    phoenixminor=`echo ${phoenixversion} | cut -d. -f2`

    magpie_phoenixmajorminorversion="$phoenixmajor.$phoenixminor"
}

Magpie_get_storm_major_minor_version() {
    local stormversion=$1

    # Get only the major and minor version, we don't care about the release
    stormmajor=`echo ${stormversion} | cut -d. -f1`
    stormminor=`echo ${stormversion} | cut -d. -f2`

    magpie_stormmajorminorversion="$stormmajor.$stormminor"
}

Magpie_get_zeppelin_major_minor_version() {
    local zeppelinversion=$1

    # Get only the major and minor version, we don't care about the release
    zeppelinmajor=`echo ${zeppelinversion} | cut -d. -f1`
    zeppelinminor=`echo ${zeppelinversion} | cut -d. -f2`

    magpie_zeppelinmajorminorversion="$zeppelinmajor.$zeppelinminor"
}
