#!/bin/bash
#############################################################################
#  Copyright (C) 2013-2015 Lawrence Livermore National Security, LLC.
#  Produced at Lawrence Livermore National Laboratory (cf, DISCLAIMER).
#  Written by Albert Chu <chu11@llnl.gov>
#  LLNL-CODE-644248
#
#  This file is part of Magpie, scripts for running Hadoop on
#  traditional HPC systems.  For details, see https://github.com/llnl/magpie.
#
#  Magpie is free software; you can redistribute it and/or modify it
#  under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  Magpie is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with Magpie.  If not, see <http://www.gnu.org/licenses/>.
#############################################################################

# These are functions to be called by magpie-run

source ${MAGPIE_SCRIPTS_HOME}/magpie/exports/magpie-exports-submission-type
source ${MAGPIE_SCRIPTS_HOME}/magpie/exports/magpie-exports-dirs
source ${MAGPIE_SCRIPTS_HOME}/magpie/exports/magpie-exports-user
source ${MAGPIE_SCRIPTS_HOME}/magpie/lib/magpie-lib-node-identification
source ${MAGPIE_SCRIPTS_HOME}/magpie/lib/magpie-lib-run
source ${MAGPIE_SCRIPTS_HOME}/magpie/lib/magpie-lib-log
source ${MAGPIE_SCRIPTS_HOME}/magpie/lib/magpie-lib-paths

# Return 0 if service up, 1 if not
__Magpie_run_check_kafka_up () {
    cd ${KAFKA_HOME}

    local serverschk=0
    local serversup=0

    for server in `cat ${KAFKA_CONF_DIR}/masters`
    do
        serverschk=`expr ${serverschk} + 1`
        local serverisup=`${MAGPIE_REMOTE_CMD:-ssh} ${MAGPIE_REMOTE_CMD_OPTS} $server ps -ef | grep -c kafka\.Kafka`
        if [ "${serverisup}" -gt "0" ]
        then
            serversup=`expr ${serversup} + 1`
        fi
    done

    for server in `cat ${KAFKA_CONF_DIR}/workers`
    do
        serverschk=`expr ${serverschk} + 1`
        local serverisup=`${MAGPIE_REMOTE_CMD:-ssh} ${MAGPIE_REMOTE_CMD_OPTS} $server ps -ef | grep -c kafka\.Kafka`
        if [ "${serverisup}" -gt "0" ]
        then
            serversup=`expr ${serversup} + 1`
        fi
    done

    echo "$serversup/$serverschk Kafka Servers are up."
    if [ "$serverschk" -eq "$serversup" ]
    then
        return 0
    fi

    return 1
}

Magpie_run_start_kafka () {
    if [ "${KAFKA_SETUP}" == "yes" ] && [ "${magpie_run_prior_startup_successful}" == "true" ]
    then
        if [ "${magpie_run_zookeeper_setup_successful}" == "0" ]
        then
            Magpie_output_internal_error "Attempt to setup Kafka without Zookeeper being setup"
            magpie_run_kafka_should_be_torndown=0
            magpie_run_kafka_setup_successful=0
            return 1
        fi

        cd ${KAFKA_HOME}

        if [ ${MAGPIE_JOB_TYPE} != "setuponly" ]
        then
            # Make variables unspecified for launching
            Magpie_make_all_local_dirs_unspecified

            echo "Starting Kafka"
            ${MAGPIE_SCRIPTS_HOME}/bin/magpie-kafka-start-all.sh

            Magpie_make_all_local_dirs_node_specific

            # My rough estimate for setup time is 30 seconds per 128 nodes
            local sleepwait=`expr ${KAFKA_WORKER_COUNT} \/ 128 \* 30`
            if [ ${sleepwait} -lt 30 ]
            then
                sleepwait=30
            fi
            echo "Waiting ${sleepwait} seconds to allow Kafka daemons to setup"
            sleep ${sleepwait}
            magpie_run_total_sleep_wait=`expr ${magpie_run_total_sleep_wait} + ${sleepwait}`
        fi

        echo "*******************************************************"
        echo "*"
        echo "* Kafka Information"
        echo "*"
        echo "* To access kafka directly, you'll want to:"
        echo "*"
        echo "*   ${MAGPIE_REMOTE_CMD:-ssh}${MAGPIE_REMOTE_CMD_OPTS:+" "}${MAGPIE_REMOTE_CMD_OPTS} ${KAFKA_MASTER_NODE}"
        if echo $MAGPIE_SHELL | grep -q csh
        then
            echo "*   setenv JAVA_HOME \"${JAVA_HOME}\""
            echo "*   setenv KAFKA_HOME \"${KAFKA_HOME}\""
            echo "*   setenv KAFKA_CONF_DIR \"${KAFKA_CONF_DIR}\""
        else
            echo "*   export JAVA_HOME=\"${JAVA_HOME}\""
            echo "*   export KAFKA_HOME=\"${KAFKA_HOME}\""
            echo "*   export KAFKA_CONF_DIR=\"${KAFKA_CONF_DIR}\""
        fi
        echo "*"
        echo "* Then you can do as you please.  To interact with Kafka you can use the applications available in:"
        echo "*"
        echo "*   \$KAFKA_HOME/${kafkacmdprefix}"
        echo "*"
        if [ "${MAGPIE_JOB_TYPE}" == "setuponly" ]
        then
            echo "* To setup, login and set environment variables per the"
            echo "* instructions above, then run:"
            echo "*"
            echo "*   $MAGPIE_SCRIPTS_HOME/bin/magpie-kafka-start-all.sh"
            echo "*"
            echo "* To end/cleanup your session & kill all daemons, login and set"
            echo "* environment variables per the instructions above, then run:"
            echo "*"
            echo "*   $MAGPIE_SCRIPTS_HOME/bin/magpie-kafka-stop-all.sh"
            echo "*"
        fi
        if [ "${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}X" != "X" ]
        then
            echo "* If running interactively, sourcing"
            echo "*"
            echo "* ${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}"
            echo "*"
            echo "* will set most common environment variables for your job."
            echo "*"
        fi
        echo "*******************************************************"

        if [ "${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}X" != "X" ]
        then
            if echo $MAGPIE_SHELL | grep -q csh
            then
                echo "setenv KAFKA_HOME \"${KAFKA_HOME}\"" >> ${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}
                echo "setenv KAFKA_CONF_DIR \"${KAFKA_CONF_DIR}\"" >> ${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}
            else
                echo "export KAFKA_HOME=\"${KAFKA_HOME}\"" >> ${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}
                echo "export KAFKA_CONF_DIR=\"${KAFKA_CONF_DIR}\"" >> ${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}
            fi
            echo "" >> ${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}
        fi

        if [ ${MAGPIE_JOB_TYPE} != "setuponly" ]
        then
            # Return 0 if service up, 1 if not
            Magpie_check_service_up "Kafka" "__Magpie_run_check_kafka_up"

            if [ $? -eq 0 ]
            then
                magpie_run_kafka_should_be_torndown=1
                magpie_run_kafka_setup_successful=1
            else
                magpie_run_kafka_should_be_torndown=1
                magpie_run_kafka_setup_successful=0
                magpie_run_prior_startup_successful=false
            fi
        else
            magpie_run_kafka_should_be_torndown=1
            magpie_run_kafka_setup_successful=1
        fi
    else
        magpie_run_kafka_should_be_torndown=0
        magpie_run_kafka_setup_successful=1
    fi
}

Magpie_run_kafka () {
    if [ "${KAFKA_JOB}" == "performance" ]
    then
        echo "*******************************************************"
        echo "* Running Performance"
        echo "*******************************************************"
        ${MAGPIE_SCRIPTS_HOME}/magpie/run/magpie-run-execute script ${MAGPIE_SCRIPTS_HOME}/magpie/job/magpie-job-kafka-performance &
        local scriptpid=$!
        Magpie_wait_script_sigusr2_on_job_timeout ${scriptpid}
    else
        Magpie_output_internal_error "KAFKA_JOB = ${KAFKA_JOB} not handled"
    fi
}

Magpie_run_stop_kafka () {
    if [ "${magpie_run_zookeeper_teardown_complete}" == "1" ]
    then
        Magpie_output_internal_warning "tearing down Kafka after Zookeeper"
    fi

    if [ "${KAFKA_SETUP}" == "yes" ] && [ "${magpie_run_kafka_should_be_torndown}" == "1" ]
    then
        if [ ${MAGPIE_JOB_TYPE} != "setuponly" ]
        then
            cd ${KAFKA_HOME}

            # Make variables unspecified for shutdown
            Magpie_make_all_local_dirs_unspecified

            echo "Stopping kafka"
            ${MAGPIE_SCRIPTS_HOME}/bin/magpie-kafka-stop-all.sh

            # Make variables specific now within Magpie
            Magpie_make_all_local_dirs_node_specific
        fi
    fi
    magpie_run_kafka_teardown_complete=1
}
