#!/bin/sh

# This script is an example of something you might like to do after a
# job is run.  It is set by the MAGPIE_POST_JOB_RUN environment
# variable.  See job submission file for details.

# Cleanup some stuff
# rm -rf /ssd/username/path

# Cleaning up on networked directory, only do on one node
if [ "${MAGPIE_CLUSTER_NODERANK}" == "0" ]
then
    # rm -rf /lustre/username/hdfsoverlustre/
fi

# Perhaps want to gather conf/log info for post-job analysis
# see magpie-gather-config-files-and-logs-script.sh script

exit 0