#!/bin/sh

# This script is an example of something you might like to do before a
# job is run.  It is set by the MAGPIE_PRE_JOB_RUN environment
# variable.  See job submission file for details.

# Get some debugging info before I run

# Run only on one node, no need to do it on all nodes
if [ "${MAGPIE_CLUSTER_NODERANK}" == "0" ]
then
    ulimit -a

    # Cat conf files for documentation

    cat ${HADOOP_CONF_DIR}/mapred-site.xml
    cat ${HADOOP_CONF_DIR}/core-site.xml
    cat ${HADOOP_CONF_DIR}/hdfs-site.xml
    cat ${HADOOP_CONF_DIR}/yarn-site.xml
fi

exit 0
