#!/bin/bash

# This script executes a basic Storm job.  It is an example of how you
# can setup a script to run an Storm job.  It is set by setting
# MAGPIE_JOB_TYPE to "script" and setting MAGPIE_SCRIPT_PATH
# environment variable to the script.  See the job submission file for
# details.
#
# Please adjust to whatever you would want to do with Storm

cd ${STORM_HOME}

command="bin/storm jar examples/storm-starter/storm-starter-topologies-0.9.2-incubating-SNAPSHOT.jar storm.starter.WordCountTopology WordCount -c storm.starter.WordCountTopology WordCount -c nimbus.host=${STORM_NIMBUS_HOST}"

echo "Running $command" >&2
$command
