#!/bin/bash
#############################################################################
#  Copyright (C) 2013-2015 Lawrence Livermore National Security, LLC.
#  Produced at Lawrence Livermore National Laboratory (cf, DISCLAIMER).
#  Written by Albert Chu <chu11@llnl.gov>
#  LLNL-CODE-644248
#
#  This file is part of Magpie, scripts for running Hadoop on
#  traditional HPC systems.  For details, see https://github.com/llnl/magpie.
#
#  Magpie is free software; you can redistribute it and/or modify it
#  under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  Magpie is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with Magpie.  If not, see <http://www.gnu.org/licenses/>.
#############################################################################

# This script is the core sparkpi running script.  For the most part,
# it shouldn't be editted.  See job submission files for configuration
# details.

source ${MAGPIE_SCRIPTS_HOME}/magpie/lib/magpie-lib-paths

# This is a job, no loading export files or libs except for minimal convenience ones

sparkpiclass="org.apache.spark.examples.SparkPi"

if [ "${SPARK_SPARKPI_SLICES}X" != "X" ]
then
    sparkpislices="${SPARK_SPARKPI_SLICES}"
else
    sparkpislices="${SPARK_WORKER_COUNT}"
fi

cd ${SPARK_HOME}

if echo ${SPARK_VERSION} | grep -q -E "1\.[0-9]\.[0-9]"
then
    # For some reason need to set MASTER environment variable for run-example, makes no sense
    if [ "${SPARK_SETUP_TYPE}" == "YARN" ]
    then
        export MASTER="yarn-client"
    else
        export MASTER="spark://${SPARK_MASTER_NODE}:${SPARK_MASTER_PORT}"
    fi
    command="${sparkcmdprefix}/run-example ${sparkpiclass} ${sparkpislices}"
elif echo ${SPARK_VERSION} | grep -q -E "[2-3]\.[0-9]\.[0-9]"
then
    command="${sparkcmdprefix}/run-example ${sparkpiclass} ${sparkpislices}"
fi

echo "Running $command" >&2
$command

exit 0
