#!/bin/bash
#############################################################################
#  Copyright (C) 2013-2015 Lawrence Livermore National Security, LLC.
#  Produced at Lawrence Livermore National Laboratory (cf, DISCLAIMER).
#  Written by Albert Chu <chu11@llnl.gov>
#  LLNL-CODE-644248
#
#  This file is part of Magpie, scripts for running Hadoop on
#  traditional HPC systems.  For details, see https://github.com/llnl/magpie.
#
#  Magpie is free software; you can redistribute it and/or modify it
#  under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  Magpie is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with Magpie.  If not, see <http://www.gnu.org/licenses/>.
#############################################################################

# This script is for running the zookeeper zookeeperruok sanity test.
# For the most part, it shouldn't be editted.  See job submission
# files for configuration details.

# This is a job, no loading export files or libs except for minimal convenience ones

zookeepernodes=`cat ${ZOOKEEPER_CONF_DIR}/workers`

if ! type nc >/dev/null 2>&1
then
    echo "Zookeeper ruok cannot be run b/c netcat ('nc' command) cannot be found"
    exit 1
fi

for zookeepernode in ${zookeepernodes}
do
    echo "Sending ruok to ${zookeepernode} ... "
    echo ruok | nc ${zookeepernode} ${ZOOKEEPER_CLIENT_PORT}
    echo
done

exit 0
