#!/bin/bash
#############################################################################
#  Copyright (C) 2013-2015 Lawrence Livermore National Security, LLC.
#  Produced at Lawrence Livermore National Laboratory (cf, DISCLAIMER).
#  Written by Albert Chu <chu11@llnl.gov>
#  LLNL-CODE-644248
#
#  This file is part of Magpie, scripts for running Hadoop on
#  traditional HPC systems.  For details, see https://github.com/llnl/magpie.
#
#  Magpie is free software; you can redistribute it and/or modify it
#  under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  Magpie is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with Magpie.  If not, see <http://www.gnu.org/licenses/>.
#############################################################################

# This script is for running the pig testpig sanity test.  For the
# most part, it shouldn't be editted.  See job submission files for
# configuration details.

source ${MAGPIE_SCRIPTS_HOME}/magpie/lib/magpie-lib-paths

# This is a job, no loading export files or libs except for minimal convenience ones

if [ "${PHOENIX_PERFORMANCEEVAL_ROW_COUNT}X" == "X" ]
then
    phoenixrowcount=100000
else
    phoenixrowcount=$PHOENIX_PERFORMANCEEVAL_ROW_COUNT
fi

# lets cd into the tmp dir because of https://issues.apache.org/jira/browse/PHOENIX-2311
cwd=`pwd`
cd ${PHOENIX_LOCAL_SCRATCHSPACE_DIR}/tmp

# Make sure the correct java gets used
command="python ${PHOENIX_HOME}/${phoenixcmdprefix}/performance.py $ZOOKEEPER_NODES_FIRST $phoenixrowcount"
echo "Running $command" >&2
$command

echo "drop table PERFORMANCE_$phoenixrowcount" > ${PHOENIX_LOCAL_SCRATCHSPACE_DIR}/tmp/cleanup.sql
echo "Cleanup Files:"
cat ${PHOENIX_LOCAL_SCRATCHSPACE_DIR}/tmp/cleanup.sql
command="python ${PHOENIX_HOME}/${phoenixcmdprefix}/sqlline.py $ZOOKEEPER_NODES_FIRST ${PHOENIX_LOCAL_SCRATCHSPACE_DIR}/tmp/cleanup.sql"
echo "Dropping Tables: $command" >&2
$command
rm ${PHOENIX_LOCAL_SCRATCHSPACE_DIR}/tmp/cleanup.sql

# and back to where we were
cd $cwd

exit 0
