#!/bin/bash
#############################################################################
#  Copyright (C) 2013-2015 Lawrence Livermore National Security, LLC.
#  Produced at Lawrence Livermore National Laboratory (cf, DISCLAIMER).
#  Written by Albert Chu <chu11@llnl.gov>
#  LLNL-CODE-644248
#
#  This file is part of Magpie, scripts for running Hadoop on
#  traditional HPC systems.  For details, see https://github.com/llnl/magpie.
#
#  Magpie is free software; you can redistribute it and/or modify it
#  under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  Magpie is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with Magpie.  If not, see <http://www.gnu.org/licenses/>.
#############################################################################

# This script is for running the pig testpig sanity test.  For the
# most part, it shouldn't be editted.  See job submission files for
# configuration details.

source ${MAGPIE_SCRIPTS_HOME}/magpie/lib/magpie-lib-paths

# This is a job, no loading export files or libs except for minimal convenience ones

if [ "${KAFKA_PERFORMANCE_RECORD_COUNT}X" == "X" ]
then
    kafkarecordcount=50000000
else
    kafkarecordcount=$KAFKA_PERFORMANCE_RECORD_COUNT
fi

if [ "${KAFKA_PERFORMANCE_RECORD_SIZE}X" == "X" ]
then
    kafkarecordsize=100
else
    kafkarecordsize=$KAFKA_PERFORMANCE_RECORD_SIZE
fi

if [ "${KAFKA_PERFORMANCE_THROUGHPUT}X" == "X" ]
then
    kafkathroughput=-1
else
    kafkathroughput=$KAFKA_PERFORMANCE_THROUGHPUT
fi

for node in `cat ${KAFKA_CONF_DIR}/masters`
do
    bootstrap="${bootstrap}${bootstrap:+","}${node}:${KAFKA_PORT}"
done

${KAFKA_HOME}/${kafkacmdprefix}/kafka-producer-perf-test.sh --topic performance --num-records ${kafkarecordcount} --record-size ${kafkarecordsize} --throughput ${kafkathroughput} --producer-props bootstrap.servers=${bootstrap}

exit 0
